version: '3.8'
services:
  database:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    user: postgres
    environment:
      POSTGRES_PASSWORD: testeFiapNaoFacaIssoEmPrd
      POSTGRES_DB: valhalla_kitchen
    volumes:
      - ./docker/01-create_db.sql:/docker-entrypoint-initdb.d/01-create_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build: ./docker
    image: renanfee/api-valhalla-kitchen:latest
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB: valhalla_kitchen
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: testeFiapNaoFacaIssoEmPrd
    depends_on:
      database:
        condition: service_healthy
