version: '3.8'
services:
  database:
    image: mysql
    networks:
      backend:
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: testeFiapNaoFacaIssoEmPrd
      MYSQL_DATABASE: valhalla_kitchen
      MYSQL_USER: fiapuser
      MYSQL_PASSWORD: testeFiapNaoFacaIssoEmPrd
    volumes:
      - ./docker/01-create_db.sql:/docker-entrypoint-initdb.d/01-create_db.sql
  api:
    build: ./docker
    networks:
      backend:
    ports:
      - "8080:8080"
    depends_on:
      - database

networks:
  backend: