version: '3.8'
services:
  database:
    image: postgres:latest
    networks:
      - backend
    restart: unless-stopped
    ports:
      - "5432:5432"
    user: postgres
    environment:
      POSTGRES_PASSWORD: testeFiapNaoFacaIssoEmPrd
      POSTGRES_DB: valhalla_kitchen
    volumes:
      - ./docker/01-create_db.sql:/docker-entrypoint-initdb.d/01-create_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build: ./docker
    networks:
      - backend
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

networks:
  backend: