apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-valhalla-kitchen-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-valhalla-kitchen
  template:
    metadata:
      labels:
        app: api-valhalla-kitchen
    spec:
      containers:
        - name: api-valhalla-kitchen-container
          image: renanfee/api-valhalla-kitchen
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: mysql-valhalla-kitchen
            - name: MYSQL_PORT
              value: '3306'
          resources:
            requests:
              memory: 120Mi
              cpu: 300m
            limits:
              memory: 200Mi
              cpu: 750m