apiVersion: v1
kind: Service
metadata:
  name: api-valhalla-kitchen-service
spec:
  selector:
    app: api-valhalla-kitchen
  ports:
    - protocol: TCP
      port: 8080  # Port your application listens on
      targetPort: 80
  type: LoadBalancer