apiVersion: v1
kind: Service
metadata:
  name: api-valhalla-kitchen-service
spec:
  selector:
    app: api-valhalla-kitchen
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
  type: LoadBalancer