server:
  servlet:
    context-path: "/api"
spring:
  datasource:
    url: jdbc:postgresql://database:5432/valhalla_kitchen
    username: postgres
    password: testeFiapNaoFacaIssoEmPrd
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
