server:
  servlet:
    context-path: "/api"
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/valhalla_kitchen?autoReconnect=true&useSSL=false
    username: fiapuser
    password: testeFiapNaoFacaIssoEmPrd
    driver-class-name: com.mysql.cj.jdbc.Driver