apiVersion: v1
kind: Service
metadata:
  name: db-valhalla-kitchen-service
spec:
  selector:
    app: db-valhalla-kitchen
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30006
  type: NodePort